version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    command: make start
    ports:
      - "3000:8000"
    volumes:
      -  .:/app
    depends_on:
      - db
